---
- hosts: 127.0.0.1
  become: yes
  tasks:
  - name: install necessary packages
    yum:
      name:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      state: present



  - name: install docker
    yum:
      name: docker-ce
      state: present

  - name: add user to docker group
    user:
      name: username_on_the_host
      group: docker
      append: yes

  - name: Make sure a service is running
    systemd:
      state: started
      name: docker.service
      enabled: true

  - name: Add repository for kubectl
    copy:
       src: ./kubectl.repo
      dest: /etc/yum.repos.d/kubernetes.repo

  - name: install kubectl
    yum:
      name: kubectl
      state: present

  - name: Download kind
    get_url:
      url: https://github.com/kubernetes-sigs/kind/releases/download/v0.3.0/kind-linux-amd64
      dest: /usr/local/bin/kind

  - name: Make kind executable
    file:
      path: /usr/local/bin/kind
      mode: u+x,g+x,o+x

  - name: reload bash_profile
    become: no
    shell: source ~/.bash_profile

  - name: create the cluster
    become: no
    shell: sh -c "kind create cluster"


                                                                                                                                                                   1,1          Haut
